2018-01-08 01:39:59,256 : ***** Transfer task : SST Binary             classification *****


2018-01-08 01:40:00,090 : Loading vectors from .vector_cache/glove.840B.300d.txt.pt
2018-01-08 01:40:03,299 : Computing embedding for test
2018-01-08 01:40:18,676 : Computed test embeddings
2018-01-08 01:40:18,676 : Computing embedding for train
2018-01-08 01:48:26,748 : Computed train embeddings
2018-01-08 01:48:26,748 : Computing embedding for dev
2018-01-08 01:48:33,195 : Computed dev embeddings
2018-01-08 01:48:33,195 : Training pytorch-LogReg with standard validation..
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "glove_lower_1sst_TODO.py", line 92, in <module>
    results_transfer = se.eval(transfer_tasks)
  File "/mnt/mmenezes/libs/SentEval/senteval/senteval.py", line 62, in eval
    self.results = {x: self.eval(x) for x in name}
  File "/mnt/mmenezes/libs/SentEval/senteval/senteval.py", line 62, in <dictcomp>
    self.results = {x: self.eval(x) for x in name}
  File "/mnt/mmenezes/libs/SentEval/senteval/senteval.py", line 104, in eval
    self.results = self.evaluation.run(self.params, self.batcher)
  File "/mnt/mmenezes/libs/SentEval/senteval/sst.py", line 79, in run
    devacc, testacc = clf.run()
  File "/mnt/mmenezes/libs/SentEval/senteval/tools/validation.py", line 247, in run
    validation_data=(self.X['valid'], self.y['valid']))
  File "/mnt/mmenezes/libs/SentEval/senteval/tools/classifier.py", line 76, in fit
    validation_split)
  File "/mnt/mmenezes/libs/SentEval/senteval/tools/classifier.py", line 55, in prepare_split
    trainX = torch.FloatTensor(trainX).cuda()
  File "/usr/local/lib/python2.7/dist-packages/torch/_utils.py", line 66, in _cuda
    return new_type(self.size()).copy_(self, async)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:66
